const SURVEY_DATA = {
  "sections": [
    {
      "key": "mesa_de_control",
      "name": "Mesa de control",
      "title": "MESA DE CONTROL",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Revisar que el expediente venga completo contra el checklist",
        "Validar identificación oficial y comprobante de domicilio del socio",
        "Verificar vigencia del acta constitutiva y los poderes del representante legal",
        "Cotejar documentos originales contra copias",
        "Revisar que el estudio de crédito venga completo y firmado",
        "Verificar avalúos y documentación de garantías",
        "Confirmar firmas del contrato y del pagaré",
        "Validar que las condiciones autorizadas coincidan con lo capturado en sistema",
        "Liberar o rechazar el expediente para disposición de recursos",
        "Devolver expedientes incompletos al área de crédito y darles seguimiento",
        "Llevar el control de folios y consecutivos de expedientes",
        "Resguardar y archivar expedientes físicos y digitales",
        "Consultar buró de crédito",
        "Revisar listas de personas bloqueadas antes de liberar",
        "Preparar carátulas y checklists para el comité de crédito",
        "Sacar expedientes cuando los pide auditoría o la CNBV",
        "Verificar que las escrituras y actos notariales estén completos en el expediente",
        "Confirmar que el testimonio notarial y su inscripción estén antes de liberar la disposición"
      ]
    },
    {
      "key": "cobranza",
      "name": "Cobranza",
      "title": "COBRANZA",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Llamar al socio antes de que se le venza el pago (recordatorio preventivo)",
        "Cobranza administrativa (atrasos de 1 a 30 días)",
        "Cobranza extrajudicial (atrasos de más de 30 días)",
        "Registrar promesas de pago y darles seguimiento",
        "Elaborar convenios de pago o reestructuras",
        "Conciliar los pagos recibidos contra el estado de cuenta del socio",
        "Aplicar pagos y verificar que se reflejen bien en el sistema",
        "Calcular intereses moratorios",
        "Elaborar el reporte de antigüedad de saldos o cartera vencida",
        "Visitar al socio en su domicilio o negocio",
        "Enviar estados de cuenta y recordatorios por correo o WhatsApp",
        "Solicitar autorización de quitas, condonaciones o prórrogas",
        "Turnar expedientes a legal para cobranza judicial",
        "Dar seguimiento a los casos que ya están con legal",
        "Actualizar la calificación de cartera o clasificación de riesgo",
        "Atender aclaraciones de socios sobre saldos, pagos y cargos"
      ]
    },
    {
      "key": "legal",
      "name": "Legal",
      "title": "LEGAL",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Elaborar y revisar contratos de crédito",
        "Elaborar pagarés y documentos de garantía",
        "Constituir y revisar garantías (hipotecaria, prendaria, fiduciaria)",
        "Dar seguimiento a inscripciones en el RUG o Registro Público de la Propiedad",
        "Presentar demandas y dar seguimiento a juicios",
        "Coordinarse con abogados externos",
        "Revisar poderes y actas constitutivas de socios personas morales",
        "Elaborar convenios judiciales y transacciones",
        "Atender requerimientos de autoridades judiciales",
        "Dar seguimiento a embargos y adjudicaciones",
        "Revisar contratos con proveedores y terceros",
        "Elaborar cartas de instrucción, finiquitos y cartas de no adeudo",
        "Asesorar a otras áreas sobre el riesgo legal de una operación",
        "Resguardar documentación legal original",
        "Revisar que las operaciones cumplan con la Ley de Uniones de Crédito",
        "Coordinar y agendar citas con la notaría",
        "Acompañar al socio a la firma ante notario",
        "Revisar proyectos de escritura antes de la firma",
        "Dar seguimiento a la inscripción de escrituras en el registro",
        "Solicitar y recabar testimonios y copias certificadas",
        "Gestionar cancelaciones de hipoteca ante notario"
      ]
    },
    {
      "key": "cumplimiento_cnbv",
      "name": "Cumplimiento CNBV",
      "title": "CUMPLIMIENTO CNBV",
      "note": "Normativa interna, PLD/FT, manuales y políticas. (Los envíos de series R y SITI van en la hoja 'Reportes CNBV'.)",
      "activities": [
        "Aplicar y actualizar el Manual de PLD/FT",
        "Integrar y actualizar los expedientes de identificación del socio (KYC)",
        "Clasificar a los socios por grado de riesgo",
        "Monitorear y detectar operaciones inusuales",
        "Elaborar reportes de operaciones relevantes, inusuales y preocupantes",
        "Consultar listas de personas bloqueadas",
        "Preparar las sesiones del Comité de Comunicación y Control",
        "Elaborar las actas del comité",
        "Capacitar al personal en PLD/FT y llevar el control de la capacitación",
        "Dar seguimiento a las recomendaciones del auditor de PLD",
        "Revisar que las políticas internas estén al día con los cambios normativos",
        "Elaborar y actualizar el manual de cumplimiento",
        "Verificar que las áreas estén cumpliendo los manuales y políticas",
        "Atender requerimientos de autoridad (CNBV, UIF, SAT)",
        "Dar seguimiento a las observaciones de la CNBV"
      ]
    },
    {
      "key": "auditoria",
      "name": "Auditoría",
      "title": "AUDITORÍA",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Elaborar el programa anual de auditoría",
        "Ejecutar pruebas de cumplimiento y sustantivas",
        "Revisar expedientes de crédito por muestreo",
        "Hacer arqueos de caja y valores",
        "Revisar conciliaciones bancarias",
        "Elaborar cédulas y papeles de trabajo",
        "Emitir informes de auditoría con observaciones",
        "Dar seguimiento a la solventación de observaciones",
        "Verificar la correcta calificación de cartera",
        "Revisar controles de sistemas, accesos y respaldos",
        "Coordinarse con el auditor externo y con el comisario",
        "Preparar información para el Consejo de Administración o Comité de Auditoría",
        "Atender visitas de inspección de la CNBV",
        "Revisar que las áreas cumplan las políticas internas"
      ]
    },
    {
      "key": "reportes_cnbv",
      "name": "Reportes CNBV",
      "title": "REPORTES CNBV",
      "note": "Entrega de información regulatoria: series R, SITI, requerimientos. (Los manuales y PLD van en la hoja 'Cumplimiento CNBV'.)",
      "activities": [
        "Elaborar y enviar los reportes regulatorios (series R)",
        "Cuadrar las cifras contra contabilidad antes de enviar",
        "Cargar la información en el SITI o portal de la CNBV",
        "Corregir y reenviar reportes rechazados",
        "Llevar el control de acuses y evidencias de envío",
        "Dar seguimiento al calendario regulatorio y sus plazos",
        "Elaborar el reporte de cartera de crédito",
        "Elaborar el reporte de índice de capitalización",
        "Reportar operaciones a la UIF",
        "Atender y responder requerimientos de información de la CNBV",
        "Coordinar con contabilidad y crédito la entrega de información",
        "Actualizar formatos y criterios cuando cambia la normatividad",
        "Preparar la información financiera para publicación",
        "Dar seguimiento a observaciones derivadas de visitas de inspección"
      ]
    },
    {
      "key": "contabilidad",
      "name": "Contabilidad",
      "title": "CONTABILIDAD",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Registrar pólizas de ingresos, egresos y diario",
        "Hacer conciliaciones bancarias",
        "Emitir y validar CFDI",
        "Descargar y conciliar CFDI del portal del SAT",
        "Calcular y enterar impuestos (ISR, IVA, retenciones)",
        "Elaborar declaraciones mensuales y anual",
        "Elaborar estados financieros",
        "Analizar auxiliares y depurar cuentas",
        "Calcular y registrar intereses devengados",
        "Registrar estimaciones preventivas para riesgos crediticios",
        "Elaborar la nómina y timbrarla",
        "Controlar activos fijos y depreciaciones",
        "Controlar cuentas por pagar y pagar a proveedores",
        "Elaborar el cierre mensual y anual",
        "Atender requerimientos del SAT",
        "Entregar información a auditoría y al área de reportes CNBV"
      ]
    },
    {
      "key": "credito",
      "name": "Crédito",
      "title": "CRÉDITO",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Prospectar y captar nuevos socios",
        "Recibir solicitudes de crédito",
        "Integrar la documentación inicial del solicitante",
        "Consultar buró de crédito",
        "Analizar los estados financieros del solicitante",
        "Elaborar el estudio de crédito",
        "Determinar la capacidad de pago",
        "Hacer visita ocular al negocio o a la garantía",
        "Proponer monto, plazo y tasa",
        "Presentar los casos al comité de crédito",
        "Dar seguimiento a la autorización",
        "Notificar al socio la resolución",
        "Coordinar la firma de contratos y la disposición de recursos",
        "Dar seguimiento al destino del crédito después del desembolso",
        "Gestionar renovaciones y ampliaciones de línea",
        "Elaborar reportes de colocación y seguimiento de metas"
      ]
    },
    {
      "key": "inversiones",
      "name": "Inversiones",
      "title": "INVERSIONES",
      "note": "Marca Sí o No en cada renglón. Los que marques Sí, detállalos en las columnas de la derecha.",
      "activities": [
        "Atender a socios interesados en invertir",
        "Explicar tasas, plazos y condiciones",
        "Elaborar los contratos de préstamo de socios",
        "Registrar las altas de inversiones",
        "Calcular los intereses a pagar",
        "Programar y ejecutar los pagos de intereses",
        "Emitir constancias de intereses y retenciones",
        "Dar seguimiento al calendario de vencimientos",
        "Gestionar renovaciones",
        "Atender solicitudes de retiro anticipado",
        "Conciliar el saldo de captación contra contabilidad",
        "Elaborar reportes de captación",
        "Vigilar la relación entre captación y colocación (liquidez)",
        "Atender aclaraciones de socios inversionistas"
      ]
    },
    {
      "key": "atencion_a_socios",
      "name": "Atención a socios",
      "title": "ATENCIÓN A SOCIOS",
      "note": "ESTA HOJA LA LLENA TODO EL MUNDO, sin importar tu área.",
      "activities": [
        "Recibir y atender llamadas de socios o prospectos",
        "Atender socios de manera presencial o en ventanilla",
        "Responder correos y mensajes de WhatsApp de socios",
        "Explicar productos, tasas y requisitos",
        "Solicitar documentación al socio o prospecto",
        "Dar seguimiento a la documentación que queda pendiente",
        "Capturar y actualizar datos del socio en el sistema",
        "Recabar información para actualizar expedientes",
        "Atender quejas y aclaraciones",
        "Notificar resoluciones al socio",
        "Dar seguimiento a compromisos que se le hicieron al socio",
        "Canalizar al socio al área que le corresponde"
      ]
    }
  ],
  "cierreQuestions": [
    "¿Qué decisión que hoy escalas te sentirías cómodo tomando tú, si tuvieras un límite claro por escrito?",
    "¿Cuál es el trámite que más veces has tenido que repetir o corregir este mes?",
    "¿Con qué frecuencia atiendes socios sin que eso sea formalmente parte de tu puesto? ¿Cuánto tiempo al día te lleva?",
    "Comentarios adicionales: cualquier cosa que no haya cabido en las hojas anteriores."
  ]
};
